# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  postgres-mcp-db:
    image: "postgres:17"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-mcp-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  
